- task: todo.yaml

  description: A CLI for querying and editing nested yaml documents for organizing
    tasks.

  subtasks:
  - task: Users can add new tasks from CLI
    status: done
    version: release-1.0
  - task: Users can read usage instructions from CLI
    version: release-1.0
  - task: Users can read usage instructions from README
    version: release-1.0
  - task: Users can modify query results in a yaml file
    version: release-1.0
    status: done
  - task: Users can define default properties for tasks in yaml header
    status: idea
  - task: Users cannot see internal fields in yaml output
    status: done
    version: release-1.0
  - task: Users can sort tasks by priority
    status: done
    version: release-1.0
  - task: Users can limit the number of matched tasks
    status: done
    version: release-1.0
  - task: Users can undo last modification from the CLI
    status: done
    version: release-1.0
  - task: Users can do a free text search of all tasks
    status: done
    version: release-1.0
  - task: Users can load tasks from stdin
    status: idea
  - task: Users can query tasks by their date
    status: done
    version: release-1.0
  - task: Users can query tasks by their status
    status: done
    version: release-1.0
  - task: Users can query tasks by their title
    status: done
    version: release-1.0
  - task: Users can load tasks from yaml file
    status: done
    version: release-1.0
  - task: Users can output query results as cards
    status: done
    version: release-1.0
  - task: Users can query tasks by their tags
    status: done
    version: release-1.0
  - task: Users can sort tasks by their due date
    version: release-1.0
    status: done
  - task: Users can output query results as YAML
    status: done
    version: release-1.0
  - task: Users can quickly set the status of a task from the CLI
    status: done
    version: release-1.0
  - task: Users can create subtasks from the CLI
    status: done
    version: release-1.0
  - state: todo
    task: Users can install the CLI as a Nix flake
    status: done
  - task: Users can mark tasks as repeating
    status: done
  - task: Users can query tasks with long text without command line boxes breaking
  - task: Users can init default todo.yaml file from the CLI
  - task: Users can remove tasks from the CLI
---

views:
  default:
    where: .status != "done" and .status != "idea"

  todo:
    where: .status == "todo"

  done:
    where: .status == "done"

  wip:
    where: .status == "wip"

  testing:
    where: .status == "testing"

  release-1.0:
    where: .version == "release-1.0"

