- name: todo.yaml

  description:
    A CLI for querying and editing nested yaml documents for organizing tasks.

  tasks:
    - name: Users can load tasks from stdin
      status: todo

    - name: Users can modify query results in a yaml file
    - name: Users can add new tasks from CLI
    - name: Users can define default properties for tasks in yaml header
    - name: Users cannot see internal fields in yaml output
    - name: Users can sort tasks by priority
    - name: Users can limit the number of matched tasks

    - name: Users can query tasks by their date
      status: done
      version: release-1.0

    - name: Users can query tasks by their status
      status: done
      version: release-1.0

    - name: Users can query tasks by their title
      status: done
      version: release-1.0

    - name: Users can load tasks from yaml file
      status: done
      version: release-1.0

    - name: Users can output query results as cards
      status: done
      version: release-1.0

    - name: Users can query tasks by their tags
      status: done
      version: release-1.0

    - name: Users can sort tasks by their due date
      version: release-1.0
      status: done

    - name: Users can output query results as YAML
      status: done
      version: release-1.0

---

default_properties:
  status: todo

views:
  default_fields:
    - name
    - description
    - status
    - version

  default:
    query: .status != "done" and .version == "release-1.0"

  todo:
    query: .status == "todo"

  done:
    query: .status == "done"

  wip:
    query: .status == "wip"

  testing:
    query: .status == "testing"

  release-1.0:
    query: .version == "release-1.0"

  tag-test:
    query: .tags | index("test")
    fields:
      - tags

