- name: Celebrate new year 2023
  date: '2023-01-01T00:00:00Z'

- name: Celebrate new year 2024
  date: '2024-01-01T00:00:00Z'

- name: Celebrate new year 2025
  date: '2025-01-01T00:00:00Z'

- name: Celebrate new year 2026
  date: '2025-01-01T00:00:00Z'

---
views:
  default:
    query: .date | fromdateiso8601 > now